language: go

env:
  - GO111MODULE=on

go:
  - 1.15.x

branches:
  only:
  - /^v*/

script:
  - go test -v ./...

after_success:
  — go get github.com/mitchellh/gox
  — gox -ldflags "-X main.version $TRAVIS_BRANCH -output "dist/bt_{{.OS}}_{{.Arch}}"
  