language: go

env:
  - GO111MODULE=on

go:
  - 1.15.x

branches:
  only:
  - main
  - /^v*/

script:
  - go test -v github.com/dkaslovsky/build-test/main.go github.com/dkaslovsky/build-test/main_test.go
